version: '3'

services:
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - DOT_START=off
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES="United States"
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HEALTH_VPN_DURATION_INITIAL=600s
      - HEALTH_VPN_DURATION_ADDITION=600s
      - HEALTH_SUCCESS_WAIT_DURATION=600s
      - LOG_LEVEL=debug
    ports:
      - 7878:7878
      - 8000:9000
      - 8989:8989
      - 9091:9091
      - 9117:9117
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    devices:
      - '/dev/dri/renderD128:/dev/dri/renderD128'
      - '/dev/dri/card0:/dev/dri/card0'
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${MEDIA_SHARE}:/media:ro
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:vpn
    volumes: 
      - ${CONFIG}/radarr:/config
      - ${RADARR_VOLUME}:/data
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:vpn
    volumes: 
      - ${CONFIG}/sonarr:/config
      - ${RADARR_VOLUME}:/data
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:vpn
    volumes: 
      - ${CONFIG}/transmission:/config
      - ${RADARR_VOLUME}:/data
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: service:vpn
    volumes:
      - ${CONFIG}/prowlarr:/config
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped

