version: '3'

services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      - TOKEN=${TOKEN}
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24
    ports:
      - 7878:7878
      - 8000:9000
      - 8989:8989
      - 9091:9091
      - 9117:9117
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${MEDIA_SHARE}:/media:ro
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:vpn
    volumes: 
      - ${CONFIG}/radarr:/config
      - ${RADARR_VOLUME}/movies:/movies
      - ${RADARR_VOLUME}/downloads:/downloads
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:vpn
    volumes: 
      - ${CONFIG}/sonarr:/config
      - ${RADARR_VOLUME}/tv:/tv
      - ${RADARR_VOLUME}/downloads:/downloads
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:vpn
    volumes: 
      - ${CONFIG}/transmission:/config
      - ${RADARR_VOLUME}/torrents:/data/torrents
      - ${RADARR_VOLUME}/downloads:/downloads
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: service:vpn
    volumes:
      - ${CONFIG}/prowlarr:/config
    environment:
      - PUID=${DOCKER_UID}
      - PGUID=${DOCKER_GID}
    restart: unless-stopped

